apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: db-tcp-port
    - protocol: UDP
      port: 5432
      targetPort: 5432
      name: db-udp-port

