apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-knex-koa-deployment
  labels:
    app: simple-knex-koa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-knex-koa
  template:
    metadata:
      labels:
        app: simple-knex-koa
    spec:
      containers:
        - name: simple-knex-koa
          image: sombriks/simple-knex-koa-example:v0.10.0-1de6b5b
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: production
            - name: PG_CONNECTION_URL
              value: postgres://postgres:postgres@db-service:5432/books
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 128Mi
              cpu: '1'
