apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: app-route
spec:
  parentRefs:
    # see gateway name inside cluster
    - name: local-gw
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /books
      backendRefs:
        - name: simple-knex-koa-service
          port: 3000
          