version: '3.5'
services:
  knex-koa-app:
    image: sombriks/simple-knex-koa-example:v0.11.0-ee4e144
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PG_CONNECTION_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db/${POSTGRES_DB:-books}
    ports:
      - '3000:3000'
    expose:
      - 3000
    healthcheck:
      test:
        - CMD
        - wget
        - '-S'
        - '--spider'
        - http://127.0.0.1:3000/status
      interval: 5s
      timeout: 10s
      retries: 30
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-books}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      interval: 30s
      timeout: 30s
      retries: 30
