name: Base Ops

on:
  workflow_call: 
    inputs:
      PUBLISH:
        type: boolean
        required: false
        default: false
      UPDATE_DESIRED_STATE:
        type: boolean
        required: false
        default: false
      DOCKER_REGISTRY:
        type: string
        required: false
        default: registry.hub.docker.com
      # DOCKER_USERNAME:
      #   type: string
      #   required: false
      #   default: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD:
      #   type: string
      #   required: false
      #   default: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERFILE:
        type: string
        required: false
        default: infrastructure/Dockerfile
      SERVICE_NAME:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      TAG:
        type: string
        required: false
        default: ${{github.ref}}-${{github.sha}}
  
jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build/Run/Test/Coverage
      run: | 
        npm ci
        npm run build --if-present
        npm run test:coverage
  
  publish-image:
    if: ${{inputs.PUBLISH == true}}
    runs-on: ubuntu-latest
    needs: [run-tests]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # see https://github.com/marketplace/actions/docker-login
    - name: Log in into Docker Hub
      uses: docker/login-action@v3
      with:
        # registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # see https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and publish image on Docker hub
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        file: ${{ inputs.DOCKERFILE }}
        platforms: linux/amd64,linux/arm64
        tags: | 
          ${{ secrets.DOCKER_USERNAME }}/${{ inputs.SERVICE_NAME }}:${{ inputs.TAG }}
          ${{ secrets.DOCKER_USERNAME }}/${{ inputs.SERVICE_NAME }}:latest
  
  update-desired-state:
    if: ${{inputs.UPDATE_DESIRED_STATE == true}}
    runs-on: ubuntu-latest
    needs: [publish-image]
    
    steps:
    - run: echo 'WIP'
