#
# _base.yml
#
# Have a base workflow is the current strategy being tested to avoid too long
# and hard to maintain several workflow files.
#
# You have this core file and the others mostly extend it by passing inputs.
#
# Feel free to copy and modify it for your own needs. Check these examples if
# in need of any: https://github.com/sombriks/gh-actions-playground
#
# @author Leonardo Silveira <sombriks@gmail.com>, MIT License
#
name: Base Ops

on:
  workflow_call: 
    inputs:
      PUBLISH:
        type: boolean
        required: false
        default: false
      UPDATE_DESIRED_STATE:
        type: boolean
        required: false
        default: false
      DOCKER_REGISTRY:
        type: string
        required: false
        default: registry.hub.docker.com
      DOCKERFILE:
        type: string
        required: false
        default: infrastructure/Dockerfile
      COMPOSEFILE:
        type: string
        required: false
        default: infrastructure/docker-compose.yml
      DEPLOYMENTFILE:
        type: string
        required: false
        default: infrastructure/k8s/workloads/deployment/app-deployment.yml
      SERVICE_NAME:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      TAG:
        type: string
        required: false
        default: ${{github.ref_name}}
  
jobs:
  prepare-git-tag:
    runs-on: ubuntu-latest
    steps:
      - id: sha-step
        name: cuts commit hash
        run: echo "hash=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
    outputs:
      git-tag: ${{inputs.TAG}}-${{steps.sha-step.outputs.hash}}

  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build/Run/Test/Coverage
      run: | 
        npm ci
        npm run build --if-present
        npm run test:coverage
  
  publish-image:
    if: ${{inputs.PUBLISH == true}}
    runs-on: ubuntu-latest
    needs: [run-tests, prepare-git-tag]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # see https://github.com/marketplace/actions/docker-login
    - name: Log in into Docker Hub
      uses: docker/login-action@v3
      with:
        # registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # see https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and publish image on Docker hub
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        file: ${{ inputs.DOCKERFILE }}
        platforms: linux/amd64,linux/arm64
        tags: | 
          ${{ secrets.DOCKER_USERNAME }}/${{ inputs.SERVICE_NAME }}:${{ needs.prepare-git-tag.outputs.git-tag }}
          ${{ secrets.DOCKER_USERNAME }}/${{ inputs.SERVICE_NAME }}:latest
  
  update-desired-state:
    if: ${{inputs.UPDATE_DESIRED_STATE == true}}
    runs-on: ubuntu-latest
    needs: [publish-image, prepare-git-tag]
    env:
      image: ${{secrets.DOCKER_USERNAME}}/${{inputs.SERVICE_NAME}}:${{ needs.prepare-git-tag.outputs.git-tag }}
    permissions:
      contents: write
    
    # we need to update docker-compose.yml and app-deployment.yml
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Pull tag changes
      run: git pull

    - name: Update docker-compose.yml
      uses: fjogeleit/yaml-update-action@v0.13.2
      with:
        valueFile: ${{inputs.COMPOSEFILE}}
        propertyPath: 'services["knex-koa-app"].image'
        value: ${{env.image}}
        commitChange: false

    - name: Update k8s app-deployment.yml
      uses: fjogeleit/yaml-update-action@v0.13.2
      with:
        valueFile: ${{inputs.DEPLOYMENTFILE}}
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{env.image}}
        commitChange: false
    
    - name: Commit desired state
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "manifests image bump to ${{env.image}}"
        git push
        
